# Generated by Django 4.0.4 on 2022-04-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_borrower_contactno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_roll', models.CharField(max_length=50)),
                ('equip_id', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('ret_date', models.DateTimeField(default=0, verbose_name='date returned')),
            ],
        ),
        migrations.RenameModel(
            old_name='Borrower',
            new_name='BorrowerInfo',
        ),
        migrations.DeleteModel(
            name='Equip',
        ),
        migrations.DeleteModel(
            name='MainTable',
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='borrower_roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttable'),
        ),
    ]
