# Generated by Django 4.0.4 on 2022-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_remove_equipmenttable_borrower_roll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttable',
            name='ret_date',
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='pub_date',
            field=models.DateTimeField(default=False),
        ),
    ]
