# Generated by Django 4.0.4 on 2022-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipmenttable_ret_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttable',
            name='ret_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
