# Generated by Django 4.0.4 on 2022-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipmenttable_ret_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmenttable',
            name='equip_id',
        ),
        migrations.RemoveField(
            model_name='equipmenttable',
            name='borrower',
        ),
        migrations.AddField(
            model_name='equipmenttable',
            name='borrower',
            field=models.ManyToManyField(to='equipment.borrower'),
        ),
        migrations.AddField(
            model_name='equipmenttable',
            name='equip',
            field=models.ManyToManyField(to='equipment.equip'),
        ),
    ]
