# Generated by Django 4.0.4 on 2022-04-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equip_remove_equipmenttable_equip_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttable',
            name='borrower',
        ),
        migrations.AddField(
            model_name='equipmenttable',
            name='borrower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='equipment.borrower'),
        ),
        migrations.RemoveField(
            model_name='equipmenttable',
            name='equip',
        ),
        migrations.AddField(
            model_name='equipmenttable',
            name='equip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equip', to='equipment.equip'),
        ),
    ]
