# Generated by Django 4.0.4 on 2022-04-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_remove_equipmenttable_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='equipment.borrower'),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip', to='equipment.equip'),
        ),
    ]
