# Generated by Django 4.0.4 on 2022-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_remove_equipmenttable_ret_status_equip_ret_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttable',
            name='ret_date',
            field=models.DateTimeField(default=0, verbose_name='date returned'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='ret_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipmenttable',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
