# Generated by Django 4.0.4 on 2022-04-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_equipmenttable_ret_date_alter_equip_ret_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='ret_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date returned'),
        ),
    ]
