# Generated by Django 4.0.4 on 2022-04-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_alter_equipmenttable_ret_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttable',
            name='ret_date',
        ),
    ]
