# Generated by Django 4.0.4 on 2022-04-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_equipmenttable_ret_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttable',
            name='ret_date',
            field=models.DateTimeField(default=0, verbose_name='date returned'),
        ),
    ]
