# Generated by Django 4.0.4 on 2022-04-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_equip_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='a',
        ),
    ]
