# Generated by Django 4.0.4 on 2022-04-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_remove_equip_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='hostelNo',
            new_name='hostel_no',
        ),
    ]
