# Generated by Django 4.0.4 on 2022-04-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_rename_hostelno_borrower_hostel_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='hostel_no',
            new_name='hostelNo',
        ),
    ]
